define({
    "_widgetLabel": "Proyectos de restauración",
    "TitleFlightPlanList": "Proyectos de restauración",
    "CreateFlightPlan": "Crear Proyecto",
    "IdFlightOrder": "Id Plan de Vuelo",
    "ProjectType": "Tipo de proyecto",
    "ProjectValue": "Valor total proyecto (Mills $)",
    "ExecuteEntity": "Entidad ejecutora",
    "FinancialEntity": "Entidad financiadora",
    "EstablishmentDate": "Fecha establecimiento",
    "LeadTime": "Plazo ejecución (meses)",
    "Comment": "Observaciones",
    "BudgetCode": "Codigo presupuestal BPIN o SECOP",
    "To": "Hasta",
    "TitleMissionCreation": "Creacion Plan de Vuelo",
    "TitleFormFlightPlan": "Datos proyecto de restauración",
    "TitleAircraftSettings": "Características Aeronave",
    "FlightPlanName": "Nombre del proyecto",
    "ConfigurationWithArmament": "Con Armamento",
    "ConfigurationWithoutArmament": "Sin Armamento",
    "Enrollment": "Matrícula",
    "Configuration": "Configuración",
    "CruiseAltitude": "Altitud Crucero",
    "ServiceCeiling": "Techo del Servicio",
    "CurrentFuel": "Combustible Actual",
    "BasicWeight": "Peso Básico",
    "ArmamentWeight": "Peso Armamento",
    "CruiseSpeed": "Velocidad Crucero",
    "CruiseFuelConsumption": "Consumo Combustible Crucero",
    "AscentSpeed": "Velocidad Ascenso",
    "AscentFuelConsumption": "Consumo Combustible Ascenso",
    "AscentRace": "Tasa Ascenso",
    "DescentSpeed": "Velocidad Descenso",
    "DescentFuelConsumption": "Consumo Combustible Descenso",
    "DescentRace": "Tasa Descenso",
    "Next": "Siguiente",
    "TitleFlightPlanDetail": "Detalle Plan de Vuelo",
    "Origin": "Origen",
    "OriginTrack": "Pista Origen",
    "NormalizedDeparture": "Salida Normalizada",
    "Destination": "Destino",
    "DestinationTrack": "Pista Destino",
    "NormalizedDestination": "Llegada Normalizada",
    "AddLeg": "Adicionar Pierna",
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "IdLeg": "Id Pierna",
    "LegFrom": "Desde",
    "LegTo": "Hasta",
    "LegLength": "Longitud (km)",
    "titleConfirmDeleteLeg": "Confirmación de Borrado",
    "contentConfirmDeleteLeg": "Est\u00E1 seguro de querer borrar este registro?"
});
  
