define({
  root: ({
        _widgetLabel: "Projects",
        TitleTabProjectData: "Project Data",
        CreateProject: "Create Project",
        SearchProjects: "Search",
        IdProject:"Id Project",
        ProjectName: "Flight Plan Name",
        ProjectType: "Project Type",
        ProjectValue: "ExecuteEntity Type",
        FinancialEntity: "Entidad financiadora",
        ExecuteEntity: "ExecuteEntity",
        EstablishmentDate: "Establishment Date",
        LeadTime: "Lead Time (months)",
        ProjectValue: "Total Value (Millis $)",
        Observations: "Observations",
        BudgetCode: "BPIN or SECOP Code",
        TitleTabProjectData: "Create/Edir Project",
        TitleTabStrategies:"Strategies",
        TitleTabRestaurationArea: "Restauration Areas",
        AddStrategies: "Add Strategy",
        BackProject: "Back",
        Project: "Project",
        CreateStrategy: "Create Strategy",
        Approach: "Approach",
        IdStrategy: "IdStrategy",
        Strategy: "Strategy",
        Area: "Area",
        Add: "Add",
        Save: "Guardar",
        Cancel: "Cancelar",
        AddAreas: "Add Restauration Area",
        BackStrategies: "Back",
        Draw: "Dibujar",
        Load: "Cargar",
        BackAreas: "Back",
        Back: "Back",
        Next: "Next",
        SaveProject: "Save Project", 

        titleConfirmDeleteLeg: "Delete Confirmation",
        contentConfirmDeleteLeg:"Are you sure delete this record"

  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 1,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
