define({
  root: ({
        _widgetLabel: "Flight Plan",
        TitleFlightPlanList: "Existing Flight Plans",
        CreateFlightPlan: "Create Flight Plan",
        IdFlightOrder: "Id Fligh tOrder",
        ProjectType: "Flight Order",
        ProjectValue: "ExecuteEntity Type",
        ExecuteEntity: "ExecuteEntity",
        From: "From",
        To: "To",
        TitleMissionCreation: "Flight Plan Creation",
        TitleFormFlightPlan: "Mission Planning",
        TitleAircraftSettings: "ExecuteEntity Settings",
        FlightPlanName: "Flight Plan Name",
        ConfigurationWithArmament: "With Armament",
        ConfigurationWithoutArmament: "Without Armament",
        Enrollment: "Enrollment",
        Configuration: "Configuration",
        CruiseAltitude: "Cruise Altitude",
        ServiceCeiling: "Service Ceiling",
        CurrentFuel:"Current Fuel",
        BasicWeight: "Basic Weight",
        ArmamentWeight: "Armament Weight",
        CruiseSpeed: "Cruise Speed",
        CruiseFuelConsumption: "Cruise Fuel Consumption",
        AscentSpeed: "Ascent Speed",
        AscentFuelConsumption: "Ascent Fuel Consumption",
        AscentRace: "Ascent Race",
        DescentSpeed: "Descent Speed",
        DescentFuelConsumption: "Descent Fuel Consumption",
        DescentRace: "Descent Race",
        ConfigurationWithArmament: "With Armament",
        ConfigurationWithoutArmament: "Without Armament",
        Next: "Next",
        TitleFlightPlanDetail: "Plan Detail",
        Origin: "Origin",
        OriginTrack: "Origin Track",
        NormalizedDeparture: "Normalized Departure",
        Destination: "Destination",
        DestinationTrack: "Destination Track",
        NormalizedDestination: "Normalized Destination",
        AddLeg: "Add Leg",
        Save: "Save",
        Cancel: "Cancel",
        IdLeg: "Id Leg",
        LegFrom: "From",
        LegTo: "To",
        LegLength: "Length (km)",
        titleConfirmDeleteLeg: "Delete Confirmation",
        contentConfirmDeleteLeg:"Are you sure delete this record"

  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 1,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
