define({
    "_widgetLabel": "Proyectos de restauración",
    "TitleTabProjectData": "Proyectos de restauración",
    "CreateProject": "Crear Proyecto",
    "SearchProjects": "Buscar",
    "IdProject": "ID Proyecto",
    "ProjectName": "Nombre del proyecto",
    "ProjectType": "Tipo de proyecto",
    "FinancialEntity": "Entidad financiadora",
    "ExecuteEntity": "Entidad ejecutora",
    "EstablishmentDate": "Fecha establecimiento",
    "LeadTime": "Plazo ejecución (meses)",
    "ProjectValue": "Valor total proyecto (Mills $)",
    "Observations": "Observaciones",
    "BudgetCode": "Codigo presupuestal BPIN o SECOP",
    "TitleTabProjectData": "Crear/Editar Proyecto",
    "TitleTabStrategies": "Estrategias",
    "TitleTabRestaurationArea": "Areas Restauracion",
    "AddStrategies": "Adicionar Estrategias",
    "BackProject": "Atrás",
    "Project": "Proyecto",
    "CreateStrategy": "Crear Estrategia",
    "Approach": "Enfoque",
    "Strategy": "Estrategia",
    "Area": "Area",
    "Add": "Agregar",
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "AddAreas": "Adicionar Areas Restauracion",
    "BackStrategies": "Atrás",
    "Draw": "Dibujar",
    "Load": "Cargar",
    "BackAreas": "Back",
    "Back": "Atrás",
    "Next": "Siguiente",
    "SaveProject": "Guardar Proyecto", 
    "CreateRecord":"Registro creado satisfactoriamente",
    "UpdateRecord":"Registro actualizado satisfactoriamente",
    "DeleteRecord":"Registro eliminado satisfactoriamente",
    "titleConfirmDeleteLeg": "Confirmación de Borrado",
    "contentConfirmDeleteLeg": "Est\u00E1 seguro de querer borrar este registro?"
});
  
